import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import NavBar from "@/ui/NavBar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Traveling Billboards",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<NavBar />{/*This is where the nav bar goes, i May change the links lateron.
				Currently it has home, thoughts, and links. Thoughts will be a page where
				 I can post my thoughts on various topics,
				 and links will be a page where I can post links to things I find interesting.	
				
				*/}
				
				{children }
				<footer className="text-center p-4 text-sm text-gray-500">
					&copy; {new Date().getFullYear()} Traveling Billboards. All rights reserved.
				</footer>
			</body>
		</html>
	);
}
